FROM node:latest as angular
WORKDIR /app
COPY package.json /app
RUN npm install -g npm
RUN npm install -g @angular/cli
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
VOLUME /var/cache/nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=angular app/dist/ /usr/share/nginx/html

CMD sed -i -e 's/$PORT/'"$PORT"'/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
